name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: write

jobs:
  update:
    name: Update&Push
    runs-on: alt-sisyphus

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git python3 python3-module-requests

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup git
        run: |
          git config --global user.name "Automatic Updater Bot"
          git config --global user.email "automatic@updater.bot"
          git config --global --add safe.directory '*'

      - name: Setup
        run: bash auto-update/update.sh
