name: Push

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: ["Auto Update"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/vala-linter-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint files
        uses: alt-gnome/linters-actions/vala@main

  checkers:
    name: Run checkers
    runs-on: alt-sisyphus

    steps:
      - name: Install git on container
        run: |
          apt-get update
          apt-get install -y git python3
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3 ./vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3 ./vala-checkers/empty_lines_checker.py .

  test-build:
    name: Test Build
    runs-on: alt-sisyphus
    needs:
      - checkers
      - lint-vala

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git python3 gcc vala meson libgee0.8-devel libgee0.8-gir-devel glib2-devel libsoup3.0-devel libjson-glib-devel gobject-introspection-devel tdlib-devel valadoc
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build -Dprefix=/usr -Ddocumentation=true

      - name: Build
        run: ninja install -C _build

      - name: Deploy pages
        uses: actions/deploy-pages@v1
        with:
          directory: ./_build/doc/valagram-1-vala
