name: CI Push

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: ["CI Auto Update"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d . -c vala-lint.conf

  checkers:
    name: Run checkers
    runs-on: ubuntu-latest

    container:
      image: alt:sisyphus

    steps:
      - name: Install git on container
        run: |
          apt-get update
          apt-get install -y git python3
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3.12 ./vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3.12 ./vala-checkers/empty_lines_checker.py .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs:
      - checkers
      - lint-vala

    container:
      image: alt:sisyphus

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git python3 gcc vala meson libgee0.8-devel glib2-devel libsoup3.0-devel libjson-glib-devel gobject-introspection tdlib-devel valadoc
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build -Dprefix=/usr -Ddocumentation=true

      - name: Build
        run: meson compile -C _build
        
      - name: Upload doc
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: _build/doc/valagram-1-vala
