name: CI Push

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: ["CI Auto Update"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d . -c vala-lint.conf

  checkers:
    name: Run checkers
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Install git on container
        run: |
          apt-get update
          apt-get install -y git python3.12
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3.12 ./vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3.12 ./vala-checkers/empty_lines_checker.py .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs:
      - checkers
      - lint-vala

    container:
      image: alt:sisyphus

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git python3 gcc vala meson libgee0.8-devel libgee0.8-gir-devel glib2-devel libsoup3.0-devel libjson-glib-devel gobject-introspection-devel tdlib-devel valadoc
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build -Dprefix=/usr -Ddocumentation=true

      - name: Build
        run: ninja install -C _build
        
      - name: Upload doc
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/doc/valagram-1-vala

  deploy:
    name: Deploy documentation
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - test-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
